version: '3'

services:
  app:
    build:
      context: ./node
      dockerfile: Dockerfile
    restart: always
    networks:
      - node-network 
    volumes:
      - ./node:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    depends_on: 
      - db    

  db:
    image: mysql:5.7               
    command: --innodb-use-native-aio=0    
    restart: always
    tty: true
    networks:
      - node-network 
    volumes:
      - ./mysql/volume:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root      

  nginx:
    build: 
      context: ./nginx
      dockerfile: Dockerfile
    networks:
    - node-network 
    ports:
      - "8080:80"
    depends_on: 
      - db
      - app

networks:
  node-network:
    driver: bridge